<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
  <el-row class="my-5">
    <el-col :span="6" :offset="9" class="grid-cell">
      <el-form :model="changePwdForm" ref="vForm" :rules="rules" label-position="top" label-width="80px"
               size="default" @submit.prevent>
        <el-form-item label="旧密码" prop="oldPwd" class="required">
          <el-input v-model="changePwdForm.oldPwd" type="password" :show-password="true" placeholder="请输入旧密码"
                    clearable></el-input>
        </el-form-item>
        <el-form-item label="新密码" prop="newPwd" class="required">
          <el-input v-model="changePwdForm.newPwd" type="password" :show-password="true" placeholder="请输入新密码"
                    clearable :minlength="3" :maxlength="20"></el-input>
        </el-form-item>
        <el-form-item label="确认新密码" prop="newPwd2" class="required">
          <el-input v-model="changePwdForm.newPwd2" type="password" :show-password="true" clearable
                    :minlength="3" :maxlength="20"></el-input>
        </el-form-item>
        <div class="flex justify-center">
          <el-button type="primary" @click="submitForm(vForm)">提交</el-button>
        </div>
      </el-form>
    </el-col>
  </el-row>

</template>

<script>
import {
  defineComponent,
  toRefs,
  reactive,
  getCurrentInstance
}
  from 'vue'
import {ElMessage} from "element-plus";
import {api} from "../../request";

export default defineComponent({
  name: 'changePassword',
  components: {},
  props: {},
  setup() {
    const state = reactive({
      changePwdForm: {
        oldPwd: "",
        newPwd: "",
        newPwd2: "",
      },
      rules: {
        oldPwd: [{
          required: true,
          message: '旧密码不能为空',
        }],
        newPwd: [{
          required: true,
          message: '新密码不能为空',
        }, {
          pattern: /^[^一-龥]+$/,
          trigger: ['blur', 'change'],
          message: ''
        }],
        newPwd2: [{
          required: true,
          message: '请确认新密码',
        }],
      },
    })
    const instance = getCurrentInstance()
    const submitForm = () => {
      instance.ctx.$refs['vForm'].validate(async valid => {
        if (!valid) return
        if (state.changePwdForm.newPwd !== state.changePwdForm.newPwd2) {
          ElMessage.error('两次输入密码不相等，请重新输入！')
          return
        }
        await api.AuthWriteControllerApi.changePassword(undefined, {
              oldPassword: state.changePwdForm.oldPwd,
              newPassword: state.changePwdForm.newPwd
            }
        )
        ElMessage.success('修改成功，下次登录生效！')
      })
    }
    const resetForm = () => {
      instance.ctx.$refs['vForm'].resetFields()
    }
    return {
      ...toRefs(state),
      submitForm,
      resetForm
    }
  }
})

</script>

<style lang="less" scoped>
div.table-container {
  table.table-layout {
    width: 100%;
    table-layout: fixed;
    border-collapse: collapse;

    td.table-cell {
      display: table-cell;
      height: 36px;
      border: 1px solid #e1e2e3;
    }
  }
}

div.tab-container {
}

.label-left-align :deep(.el-form-item__label) {
  text-align: left;
}

.label-center-align :deep(.el-form-item__label) {
  text-align: center;
}

.label-right-align :deep(.el-form-item__label) {
  text-align: right;
}

.custom-label {
}

.static-content-item {
  min-height: 20px;
  display: flex;
  align-items: center;

  :deep(.el-divider--horizontal) {
    margin: 0;
  }
}

</style>