<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
  <el-row class="my-5">
    <el-col :span="6" :offset="9" class="grid-cell">
      <el-form :model="changePwdForm" ref="vChangePwdForm" :rules="rules" label-position="top" label-width="80px"
               size="default" @submit.prevent>
        <el-form-item label="用户头像地址" prop="avatarInput">
          <el-input v-model="changePwdForm.avatarInput" type="text" clearable></el-input>
        </el-form-item>
        <el-form-item label="用户昵称" prop="nickName" class="required">
          <el-input v-model="changePwdForm.nickName" type="text" clearable></el-input>
        </el-form-item>
        <div class="static-content-item flex justify-center">
          <el-button type="primary" @click="submitForm">提交</el-button>
        </div>
      </el-form>
    </el-col>
  </el-row>

</template>

<script>
import {
  defineComponent,
  toRefs,
  reactive,
  getCurrentInstance
}
  from 'vue'
import {ElMessage} from "element-plus";
import {userUserStore} from "../../store/modules/user";
import {changeCurrentUserInfoApi} from "../../request/user";

export default defineComponent({
  name: 'userInfo',
  components: {},
  props: {},
  setup() {
    const currentUser = userUserStore.currentUser;
    const state = reactive({
      changePwdForm: {
        avatarInput: currentUser.avatar,
        nickName: currentUser.nickName,
      },
      rules: {
        avatar: [{
          required: true,
          message: '字段值不可为空',
        }],
        nickName: [{
          required: true,
          message: '字段值不可为空',
        }],
      },
      avatarFileList: [],
      avatarUploadHeaders: {},
      avatarUploadData: {},
    })
    const instance = getCurrentInstance()
    const submitForm = () => {
      instance.ctx.$refs['vChangePwdForm'].validate(async valid => {
        if (!valid) return
        await changeCurrentUserInfoApi(state.changePwdForm.nickName, state.changePwdForm.avatarInput)
        userUserStore.updateInfo(state.changePwdForm.nickName, state.changePwdForm.avatarInput)
        ElMessage.success('修改成功')
      })
    }
    const resetForm = () => {
      instance.ctx.$refs['vChangePwdForm'].resetFields()
    }
    return {
      ...toRefs(state),
      submitForm,
      resetForm,
    }

  }
})

</script>

<style lang="less" scoped>
div.table-container {
  table.table-layout {
    width: 100%;
    table-layout: fixed;
    border-collapse: collapse;

    td.table-cell {
      display: table-cell;
      height: 36px;
      border: 1px solid #e1e2e3;
    }
  }
}

div.tab-container {
}

.label-left-align :deep(.el-form-item__label) {
  text-align: left;
}

.label-center-align :deep(.el-form-item__label) {
  text-align: center;
}

.label-right-align :deep(.el-form-item__label) {
  text-align: right;
}

.custom-label {
}

.static-content-item {
  min-height: 20px;
  display: flex;
  align-items: center;

  :deep(.el-divider--horizontal) {
    margin: 0;
  }
}

</style>